[package]
name = "keriox"
version = "0.1.0"
authors = ["Decentralized Identity Foundation"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ursa = { version = "0.3", default-features = false, features = ["portable"]}
wasm-bindgen = { version = "0.2", features = ["nightly"] }
base64 = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.10"
